name: actions workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: simple java script action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Koti
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
      - name: Find the path and list files
        run: pwd && ls
