name: actions workflow

on:
#   schedule:
#     - cron: '0/5 * * * *'
#   push:
#     branches-ignore: [master]
#   schedule:
#     - cron: "0/2 * * * 1,2,3,4,5"

  push:
    branches:
      - master
      - develop
      - 'feature/*'
  # tags:
  #   - v1
  # push:
#   schedule:
#     - cron: '0/5 * * * *'
  #   - cron: "0/6 * * * *"
  # repository_dispatch:
  #   types: [build]
  # pull_request:
  #   types: [closed, assigned, reopened, opened]

  


jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
#         if: github.ref == 'refs/heads/develop' 
        uses: actions/checkout@v2
        
      - name: tags before
        run: git tag -l
      - name: checking
        run: |
          echo ${{ github.ref }}
          git fetch --prune --unshallow --tags
      - name: tags
        run: 
          git tag -l
          echo ${{ github.ref }}
        
#       - name: payload
#         run: echo "${{ github.event.client_payload.env }}"
#       - name: simple java script action
#         id: greet
#         uses: actions/hello-world-javascript-action@v1
#         with:
#           who-to-greet: Koti
#       - name: Log Greeting Time
#         run: echo "${{ steps.greet.outputs.time }}"
#       - name: Find the path and list files
#         run: |
#           pwd
#           ls -a
#           echo $GITHUB_SHA
#           echo $GITHUB_REPOSITORY
#           echo $GITHUB_WORKSPACE
#           echo "${{ github.token }}"
#           # git clone git@github:$GITHUB_REPOSITORY
#           # git checkout $GITHUB_SHA
#       - name: Checkout the repo
#         uses: actions/checkout@v1

#       - name: Find the path and list files after checkout
#         run: |
#           pwd
