name: matrix

on: pull_request

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        node_version: [6, 8, 10]
        exclude:
          - os: ubuntu-latest
            node_version: 6
        include:
          - os: ubuntu-latest
            node_version: 4
    runs-on: ${{ matrix.os }}
    steps:
      - name: Log node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Log again node version
        run: node -v
      
        